<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x1 = [4,8,7,6,9]
type(x1)

# By default numpy uses ndarray
a1 = np.array(x1)
type(a1)

numpy.ndarray

In [ ]:
x2 = [6,9,1,3,2]
a2 = np.array([x1,x2])
print(a2)
type(a2)

[[4 8 7 6 9]
 [6 9 1 3 2]]


numpy.ndarray

1. Where Binary search tree might fail?
2. At which condition we can replace Logistic Regression with Decision Tree?

In [ ]:
a = [range(1,11)]
print(a)

a = list(range(1,11))
print(a)

[range(1, 11)]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a1 = np.arange(11)
print(a1)

a2 = np.arange(3, 14)
print(a2)

a3 = np.arange(5,25,3)
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10 11 12 13]
[ 5  8 11 14 17 20 23]


In [ ]:
a4 = np.arange(24,5,-2)
a4

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6])

In [ ]:
# including 10 and 30 and the array size will be 7 and the gap between 2 number
# will be the same and what will be the gap that will python decides.
x1 = np.linspace(10,30,7)
print(f'{x1}\n')

# endpoint will not include 30 in the array it will be 30-1 = 29, 29 will be the last elements
x2 = np.linspace(10,30,7,endpoint=False)
print(x2)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.        ]

[10.         12.85714286 15.71428571 18.57142857 21.42857143 24.28571429
 27.14285714]


In [ ]:
x1 = np.append(x1,3)
print(f'{x1}\n')

x2 = np.array([2,9,8])

x3 = np.concatenate([x1,x2])
print(x3)


[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.          3.          3.          3.          3.          3.
  3.        ]

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.          3.          3.          3.          3.          3.
  3.          2.          9.          8.        ]


ValueError: cannot delete array elements

In [ ]:
x1 = np.delete(x1, 8)
print(x1)

a4 = np.insert(a4,3,7)
print(a4)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.          3.        ]
[24 22 20  7  7 18 16 14 12 10  8  6]


Interview question might ask:
1. basic que: banana peel (dangerous type of question)
2. performance question (you will have some output out of it)
3. tie breaking question (distinguishing between other candidates)

In [ ]:
a1 = np.array([2,4,5,6,2,5,6,8])
len(a1)
a2 = a1.reshape(4,2)
print(a2)
a3 = a1.reshape(2,4)
print(a3)
#a4 = a1.reshape(3,3) # ValueError: cannot reshape array of size 8 into shape (3,3)
#print(a4)
a5 = a1.reshape(2,2,2) # this will give you 2 2D array into 1 3D array
print(a5)
'''
[[[2 4]
  [5 6]]
 [[2 5]
  [6 8]]]
'''

a6 = a1.reshape(-1,1)
print(a6)

a7 = a1.reshape(-1,)
print(a7)

[[2 4]
 [5 6]
 [2 5]
 [6 8]]
[[2 4 5 6]
 [2 5 6 8]]
[[[2 4]
  [5 6]]

 [[2 5]
  [6 8]]]
[[2]
 [4]
 [5]
 [6]
 [2]
 [5]
 [6]
 [8]]
[2 4 5 6 2 5 6 8]


In [ ]:
# Error in code if it will runs
'''
a6 = a1.reshape(-1,-1) # ValueError: can only specify one unknown dimension
print(a6)

a6 = a1.reshape(0,1) # ValueError: cannot reshape array of size 8 into shape (0,1)
print(a6)

a6 = a1.reshape(,1) # SyntaxError: invalid syntax
print(a6)

a6 = a1.reshape(-1,) # Runs
print(a6)
'''

[2 4 5 6 2 5 6 8]


In [ ]:
print(a2[2])
print(a2[2,:])
print(a2[:,1])
print(a2[[2,3],:]) # multiple rows at a time
print(a2[1,[0,1]]) # multiple

[2 5]
[2 5]
[4 6 5 8]
[[2 5]
 [6 8]]
[5 6]


In [ ]:
new_col = np.array([3,4,5,2])
new_col = new_col.reshape(-1,1)

a2 = np.hstack([a2,new_col])

print(a2)

array([[2, 4, 3, 3],
       [5, 6, 4, 4],
       [2, 5, 5, 5],
       [6, 8, 2, 2]])

In [ ]:
new_row = np.array([3,2,6,9])

a2 = np.vstack([a2,new_row])
print(a2)

[[2 4 3 3]
 [5 6 4 4]
 [2 5 5 5]
 [6 8 2 2]
 [3 2 6 9]]


In [ ]:
a2 = np.delete(a2, 3, axis=1)
print(a2)

[[2 4 3]
 [5 6 4]
 [2 5 5]
 [6 8 2]
 [3 2 6]]


In [ ]:
# a2 = np.insert(a2,3,[12,4,52],axis=0)
print(a2)

[[24 22 14 20]
 [12  4  4 52]
 [ 7  7 33 18]
 [16 14  5 12]
 [10  8  1  6]]


In [ ]:
a2 = np.insert(a2,2,[14,4,33,5,1],axis=1)
print(a2)

[[24 22 14 20]
 [12  4  4 52]
 [ 7  7 33 18]
 [16 14  5 12]
 [10  8  1  6]]


In [ ]:
np.delete(a2,[1,3],axis=0)

array([[24, 22, 14, 20],
       [ 7,  7, 33, 18],
       [10,  8,  1,  6]])

# Bro

In [ ]:
# Broad-casting: make an array different from list
b1 = np.array([4,7,6,8,9])
b2 = np.array([4,2,7,6,3])

b1 + 5
# Broadcasting make it possible to repeat the same operation across all the values

2*b1 + 5
b1 + b2


array([ 8,  9, 13, 14, 12])

In [ ]:
b3 = np.array([3,4,52,2]) # ValueError: operands could not be broadcast together with shapes (5,) (4,)
# broadcasting doesn't support recycling the array like in R lang.
b1 + b3

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
b1 = np.array([2,4,5,6,2,6,8,2,1,4,8,2])
b2 = b1.reshape(-1,4)
print(b2)

[[2 4 5 6]
 [2 6 8 2]
 [1 4 8 2]]


In [ ]:
b3 = np.array([2,4,6,7])
b2 + b3

array([[ 4,  8, 11, 13],
       [ 4, 10, 14,  9],
       [ 3,  8, 14,  9]])

In [ ]:
b4 = np.array([5,7,2])
b5 = b4.reshape(-1,1)
print(b5) # b5 will decide will it be added row-wise/column-wise with b2
b2 + b5
b1[[1,3,4]] # multiple indies

[[5]
 [7]
 [2]]


array([[ 7,  9, 10, 11],
       [ 9, 13, 15,  9],
       [ 3,  6, 10,  4]])

In [ ]:
print(b1)
# Q1. Where are the values which are greater than 4
ind = np.where(b1>4) # input to the np.where is a condition that needs to be checked, output of where command is indies where the condition is found to be true.
print(ind)
ind = np.where(b1>4) # for 2D array
print(ind) # output will be different, output: (array([0, 0, 1, 1, 2]), array([2, 3, 1, 2, 2]))

# Q2. How many values are greater than 4
len(ind) # length of tuple
len(ind[0]) # length of array inside the tuple
(b1>4).sum()

# Q3. What are the values which are greater than 4
print(b1[ind]) # it may give you error in this command
print(b1[ind[0]])
b1[b1>4]

[2 4 5 6 2 6 8 2 1 4 8 2]
(array([ 2,  3,  5,  6, 10]),)
(array([ 2,  3,  5,  6, 10]),)
[5 6 6 8 8]
[5 6 6 8 8]


array([5, 6, 6, 8, 8])

In [ ]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols
# x2 = x1.reshape(12,4)

x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically

b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
c = sorted(b)[::-1]    # sorts the array in the decreasing order
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [162]:
r1 = [5,8,3]
r2 = r1*3
print(r2)

r3 = np.array([2,6,5])
r4 = np.repeat(r1,[2,6,5])
print(r4)

[5, 8, 3, 5, 8, 3, 5, 8, 3]
[5 5 8 8 8 8 8 8 3 3 3 3 3]


In [164]:
a1 = np.array([4,7,6,1,3,8,7,2])
np.sort(a1) # values will be sorted
np.argsort(a1) # indices of the sort values
a1[np.argsort(a1)] # sorted array

array([1, 2, 3, 4, 6, 7, 7, 8])

In [172]:
a1 = np.array([6,5,4,8,7,6,2,2,5,7,1,8,1])
print(np.unique(a1)) # unique values
print(np.unique(a1,return_counts=True)) # how many times each value is occuring
print(np.unique(a1,return_index=True)) # indices of first values will occurs
print(np.unique(a1,return_inverse=True)) # indices of sorted values
print(np.where(a1==1)) # indices where 1 value is occured

[1 2 4 5 6 7 8]
(array([1, 2, 4, 5, 6, 7, 8]), array([2, 2, 1, 2, 2, 2, 2]))
(array([1, 2, 4, 5, 6, 7, 8]), array([10,  6,  2,  1,  0,  4,  3]))
(array([1, 2, 4, 5, 6, 7, 8]), array([4, 3, 2, 6, 5, 4, 1, 1, 3, 5, 0, 6, 0]))
(array([10, 12]),)
