<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [9]:
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])

print(np.intersect1d(a1,a2))
print(np.union1d(a1,a2))

print(np.in1d(a1,a2)) # DeprecationWarning: instead use below command
print(np.isin(a1,a2))

[3 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False]
[ True False  True False  True False]


/tmp/ipykernel_5458/652233031.py:7: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a1,a2))


In [6]:
print(np.setdiff1d(a1,a2))
print(np.setdiff1d(a2,a1))

[1 7 9]
[ 2  4  5 10]


In [11]:
# either only in a1 or in a2
print(np.setxor1d(a1,a2))
print(np.where(np.isin(a1,a2))) # this is intersection of a1 and a2


[ 1  2  4  5  7  9 10]
(array([0, 2, 4]),)


Matrix multiplication:

Critiria -> No. of rows of A = No. of cols of B

Dot Product: There result will always be scaler, it might be negative and 0.

If result is 0 then it means vectors are perpendicular(orthogonal)

Then you have to find the dot product with |v1||v2|cos0



In [12]:
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])

print(np.dot(x1,x2))

-4


In [15]:
# Linear algebra
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])
print(np.linalg.det(x3)) # determinant value

# cross product
print(np.cross(x1,x2))

-1.0


array([ -5, -14, -13])

In [18]:
from numpy import random

np.random.rand(10)
np.random.randint(5,50)
np.random.randint(5,50,15)

array([15, 19, 44, 41, 27, 40, 31, 44,  6,  7, 48, 32, 24, 49, 33])